#!/bin/sh

sudo apt-get update
sudo apt-get install vsftpd

#sudo nano /etc/vsftpd.conf


#In this file find the following lines and un-comment them by deleting the # character :

anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=YES
Add the following lines to the end of the file :

user_sub_token=$USER
local_root=/home/$USER/ftp
Save and exit using CTRL-X, Y and ENTER




chmod a-w /home/pi/Downloads
