#!/bin/sh
sudo apt-get update && sudo apt-get install transmission-daemon

sudo systemctl stop transmission-daemon

wget https://raw.githubusercontent.com/barryallenx509/pisetup/master/transmission_settings.json
mv transmission_settings.json /etc/transmission-daemon/settings.json






sudo ufw allow 9091,51413/tcp

sudo systemctl start transmission-daemon













